(setq inhibit-startup-message t)
;;(when (fboundp 'menu-bar-mode) (menu-bar-mode -1))
(when (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(when (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
(set-default-font "Hack 13")
(load-theme 'dracula t)
(provide 'setup-theme)
